### ISSUE TITLE
1.2 tracking bug

### ISSUE THREAD

**Issue by kr** [chain/chain#1035]
- [x] full integration test (hsm, multiple coreds, customer sim test drivers, migration from 1.1.3)
- [x] testing on windows
- [x] more protocol testing (jackson has this ongoing)
- [x] migrating access tokens from 1.1 to 1.2 (#1015)
- [x] protecting raft endpoints with auth (#1029)
- [x] moving postgres data directory into APPDATA for windows installer (#1021)
- [x] be sure to return 2xx for `/dashboard/` things (hard code hack in authn) (#1121)
- [x] make errNotAuthn depend on loopback build tag (#1121)
- [x] java sdk changes for client authn (#984)
- [x] duplicate output id bug (https://github.com/chain/chain/issues/1018)
- [x] validate guard data for new x509 grants
- [x] make a separate policy for getting block signatures (#1063)
- [x] corectl should take a policy name in create-token (#1042)
- [x] corectl should have a way to grant and revoke perms (#1043)
- [x] make generator resistant to signing failures (#1034)
- [x] require TLS in production (server build) (#1059)
- [x] remove unsightly raft logging (#1091)
- [x] protected grant for raft cluster members

**Comment by kr** [comment]
Closing this, since all items are done.
