### ISSUE TITLE
logging improvements meta-bug

### ISSUE THREAD

**Issue by kr** [chain/chain#753]
Some tweaks I'd like to make to package chain/log, in no particular order:

- [x] Rename Write and Fatal to Printkv and Fatalkv. This is an attempt to imitate the naming scheme of package log, but with "kv" in place of "f" to indicate key-value arguments rather than a format string. It's also an attempt to look less like io.Writer.
- [x] Rename Messagef to Printf.
- [ ] Make the context optional in Printkv and Fatalkv (and maybe even in Printf).
- [x] Make `ctx = AddPrefixkv(ctx, kv...)` in addition to the existing `SetPrefix(kv...)`.
- [x] Update chain/net/http/reqid to use log.WithPrefixkv and remove the dependency from log on reqid.
- [ ] Simplify the signature and behavior of log.Error.
- [ ] Make Error always print a stack trace -- if one isn't provided as a parameter, it can capture a fresh one.
- [x] Make an easier+better way for helper packages to skip themselves for the auto-generated "at" field. Right now if we have a logging function in some other package, every place that calls the helper will see `at=helper.go:123` instead of the real place that is producing the log line.
- [ ] Perhaps change Printf to print unstructured text directly to the log, instead of putting the whole formatted string in a single `message` field.
- [ ] Print the timestamp at the beginning of the line.
